version: 2
jobs:
  build:
    docker:
      - image circleci/node:8.10.0
    steps:
      - checkout
      - run: npm install npm@6.0.0 -g
      - run: npm install npm-cli-login -g
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm-cli-login
      - run: npm ci
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    docker:
      - image circleci/node:8.10.0
    steps:
      - checkout
      - run: npm test
  deploy:
    docker:
      - image circleci/node:8.10.0
    steps:
      - checkout
      - run: npm publish
workflows:
  version: 2
  build_test_deploy:
    - build
        tags:
          only: /.*/
    - test:
        requires:
          - build
        tags:
          only: /.*/
    - deploy:
        requires:
          - test
        filters:
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*\.[0-9]+)?/
          branches:
            ignore: /.*/
